'use client';

import { useState } from 'react';

const GITHUB_URL = 'https://github.com/sarthakagrawal927/CodeVetter';
const DOWNLOAD_URL = 'https://github.com/sarthakagrawal927/CodeVetter/releases/latest';

const FAQ_ITEMS = [
  {
    question: 'What is CodeVetter?',
    answer: 'CodeVetter is a desktop app that reviews code generated by AI agents. It catches over-engineering, hallucinated APIs, copy-paste code, and hardcoded secrets — then sends findings back to the agent for automated fixes.',
  },
  {
    question: 'Is it free?',
    answer: 'Yes, CodeVetter is completely free and open source under the MIT license. You only need an API key from your preferred AI provider (OpenAI, Anthropic, etc.).',
  },
  {
    question: 'Does it need internet?',
    answer: 'CodeVetter runs entirely on your machine. The only network call is to the AI provider for generating the review. No data is sent to CodeVetter servers — there are none.',
  },
  {
    question: 'What platforms are supported?',
    answer: 'macOS 12+ currently. Windows and Linux support is planned.',
  },
  {
    question: 'What AI providers are supported?',
    answer: 'Any provider with an OpenAI-compatible API — OpenAI, Anthropic, Google, and local models via Ollama or LM Studio.',
  },
  {
    question: 'How is this different from GitHub Copilot code review?',
    answer: 'CodeVetter is specifically designed for AI agent output. It catches the patterns agents get wrong: bloated abstractions, hallucinated package APIs, unnecessary complexity. It also creates a feedback loop — sending findings back to the agent for automated fixes.',
  },
  {
    question: 'Can it review GitHub PRs?',
    answer: 'Yes. Connect via a GitHub Personal Access Token and CodeVetter will review PRs directly. For local code, it reviews diffs against your current branch.',
  },
];

function CheckIcon() {
  return (
    <svg className="shrink-0" width="18" height="18" viewBox="0 0 24 24" fill="none" stroke="#22c55e" strokeWidth="2.5" strokeLinecap="round" strokeLinejoin="round">
      <polyline points="20 6 9 17 4 12" />
    </svg>
  );
}

function AccordionItem({ question, answer, isOpen, onToggle, isLast }) {
  return (
    <div className={isLast ? '' : 'border-b border-edge'}>
      <button
        type="button"
        className="w-full flex items-center justify-between py-5 bg-transparent border-none cursor-pointer text-left font-[inherit]"
        onClick={onToggle}
        aria-expanded={isOpen}
      >
        <span className="text-base font-semibold text-content pr-4">{question}</span>
        <svg
          className={`shrink-0 text-muted transition-transform duration-200 ${isOpen ? 'rotate-180' : ''}`}
          width="20" height="20" viewBox="0 0 24 24"
          fill="none" stroke="currentColor" strokeWidth="2"
          strokeLinecap="round" strokeLinejoin="round"
        >
          <polyline points="6 9 12 15 18 9" />
        </svg>
      </button>
      <div className={`overflow-hidden transition-all duration-250 ${isOpen ? 'max-h-80 pb-5' : 'max-h-0'}`}>
        <p className="text-muted text-sm leading-relaxed">{answer}</p>
      </div>
    </div>
  );
}

export default function LandingPage() {
  const [openFaq, setOpenFaq] = useState(null);

  return (
    <>
      {/* NAV */}
      <nav className="sticky top-0 z-50 flex items-center justify-between px-5 md:px-8 h-16 bg-page/80 backdrop-blur-2xl border-b border-edge-subtle">
        <div className="flex items-center justify-between w-full max-w-[1200px] mx-auto">
          <div className="flex items-center gap-2.5 font-bold text-base tracking-tight">
            <div className="w-7 h-7 bg-amber rounded-md grid place-items-center text-[0.65rem] text-page font-black -tracking-wider">CV</div>
            CodeVetter
          </div>
          <div className="flex gap-3 items-center">
            <a href={GITHUB_URL} className="inline-flex items-center px-3 py-2 text-sm font-medium text-muted hover:text-content transition-colors" target="_blank" rel="noopener noreferrer">
              GitHub
            </a>
            <a href={DOWNLOAD_URL} className="inline-flex items-center px-5 py-2 rounded-lg text-sm font-semibold bg-amber text-page hover:bg-amber-light hover:shadow-[0_0_20px_rgba(245,158,11,0.25)] transition-all">
              Download
            </a>
          </div>
        </div>
      </nav>

      {/* HERO */}
      <section className="max-w-[1200px] mx-auto pt-28 md:pt-32 pb-16 md:pb-20 px-5 md:px-8 flex flex-col items-center text-center">
        <div className="inline-flex items-center gap-2 px-3.5 py-1 bg-amber-dim border border-amber-border rounded-full text-xs font-medium text-amber-light mb-8">
          <span className="w-1.5 h-1.5 rounded-full bg-amber animate-pulse-dot" />
          Free &middot; Open Source &middot; macOS
        </div>
        <h1 className="text-[clamp(1.85rem,5.5vw,4rem)] font-extrabold leading-[1.1] -tracking-wider mb-6 max-w-[720px]">
          The quality gate for <span className="hero-highlight">AI-generated code</span>
        </h1>
        <p className="text-muted text-lg leading-relaxed mb-10 max-w-[600px]">
          CodeVetter reviews code from AI agents, catches bloat and hallucinated APIs,
          and sends findings back to the agent to fix. Locally or on GitHub PRs.
        </p>
        <div className="flex gap-3 flex-wrap justify-center">
          <a href={DOWNLOAD_URL} className="inline-flex items-center gap-2 px-7 py-3.5 rounded-xl text-base font-semibold bg-amber text-page hover:bg-amber-light hover:shadow-[0_0_20px_rgba(245,158,11,0.25)] transition-all">
            <svg width="18" height="18" viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="2.5" strokeLinecap="round" strokeLinejoin="round"><path d="M21 15v4a2 2 0 01-2 2H5a2 2 0 01-2-2v-4"/><polyline points="7 10 12 15 17 10"/><line x1="12" y1="15" x2="12" y2="3"/></svg>
            Download for macOS
          </a>
          <a href={GITHUB_URL} className="inline-flex items-center gap-2 px-7 py-3.5 rounded-xl text-base font-medium border border-edge text-content hover:bg-card hover:border-muted transition-all" target="_blank" rel="noopener noreferrer">
            View Source
          </a>
        </div>
      </section>

      <hr className="border-none border-t border-edge-subtle max-w-[1200px] mx-auto" />

      {/* FEATURES */}
      <section className="max-w-[1200px] mx-auto py-16 md:py-24 px-5 md:px-8">
        <div className="text-center mb-16">
          <span className="inline-block font-mono text-xs font-semibold tracking-widest uppercase text-amber mb-3">[ features ]</span>
          <h2 className="text-[clamp(1.75rem,4vw,2.5rem)] font-bold -tracking-wide mb-3">What it catches</h2>
          <p className="text-muted text-lg max-w-[560px] mx-auto leading-relaxed">Purpose-built for the patterns AI agents get wrong.</p>
        </div>
        <div className="grid grid-cols-1 md:grid-cols-3 gap-4 md:gap-5">
          <div className="bg-card border border-edge rounded-2xl p-8 transition-all hover:border-amber-border hover:bg-card-hover hover:shadow-[0_0_40px_rgba(245,158,11,0.04)]">
            <span className="inline-block font-mono text-[0.7rem] font-semibold tracking-wide uppercase px-2.5 py-1 rounded bg-amber-dim text-amber mb-4">review</span>
            <h3 className="text-base font-semibold mb-2 -tracking-tight">Review agent code</h3>
            <p className="text-muted text-sm leading-relaxed">Runs AI-powered review on local diffs or GitHub PRs. Catches over-engineering, copy-paste, hallucinated APIs, and hardcoded secrets.</p>
          </div>
          <div className="bg-card border border-edge rounded-2xl p-8 transition-all hover:border-amber-border hover:bg-card-hover hover:shadow-[0_0_40px_rgba(245,158,11,0.04)]">
            <span className="inline-block font-mono text-[0.7rem] font-semibold tracking-wide uppercase px-2.5 py-1 rounded bg-green-dim text-green mb-4">automation</span>
            <h3 className="text-base font-semibold mb-2 -tracking-tight">Feedback loop</h3>
            <p className="text-muted text-sm leading-relaxed">When review fails, findings are sent back to the agent as fix instructions. Re-reviews automatically until the code passes or max attempts hit.</p>
          </div>
          <div className="bg-card border border-edge rounded-2xl p-8 transition-all hover:border-amber-border hover:bg-card-hover hover:shadow-[0_0_40px_rgba(245,158,11,0.04)]">
            <span className="inline-block font-mono text-[0.7rem] font-semibold tracking-wide uppercase px-2.5 py-1 rounded bg-purple-dim text-purple mb-4">orchestration</span>
            <h3 className="text-base font-semibold mb-2 -tracking-tight">Orchestrate agents</h3>
            <p className="text-muted text-sm leading-relaxed">Kanban board with agent personas. Assign tasks, track progress, manage concurrency. Plan, code, review pipeline runs autonomously.</p>
          </div>
        </div>
      </section>

      <hr className="border-none border-t border-edge-subtle max-w-[1200px] mx-auto" />

      {/* HOW IT WORKS */}
      <section className="max-w-[1200px] mx-auto py-16 md:py-24 px-5 md:px-8">
        <div className="text-center mb-16">
          <span className="inline-block font-mono text-xs font-semibold tracking-widest uppercase text-amber mb-3">[ how it works ]</span>
          <h2 className="text-[clamp(1.75rem,4vw,2.5rem)] font-bold -tracking-wide">Three steps to better agent code</h2>
        </div>
        <div className="grid grid-cols-1 md:grid-cols-3 gap-4 md:gap-8 relative">
          <div className="steps-connector hidden md:block" />
          <div className="text-center p-6 md:p-8 relative">
            <div className="w-12 h-12 rounded-full bg-amber-dim border border-amber-border text-amber font-bold text-lg inline-grid place-items-center mb-5">1</div>
            <h3 className="text-base font-semibold mb-2 -tracking-tight">Point at code</h3>
            <p className="text-muted text-sm leading-relaxed">Open a local diff or connect a GitHub PR via Personal Access Token. CodeVetter picks up the changes automatically.</p>
          </div>
          <div className="text-center p-6 md:p-8 relative">
            <div className="w-12 h-12 rounded-full bg-amber-dim border border-amber-border text-amber font-bold text-lg inline-grid place-items-center mb-5">2</div>
            <h3 className="text-base font-semibold mb-2 -tracking-tight">AI reviews</h3>
            <p className="text-muted text-sm leading-relaxed">Your chosen AI provider analyzes the diff against configurable rules. Flags bloat, hallucinated APIs, missing error handling, and more.</p>
          </div>
          <div className="text-center p-6 md:p-8 relative">
            <div className="w-12 h-12 rounded-full bg-amber-dim border border-amber-border text-amber font-bold text-lg inline-grid place-items-center mb-5">3</div>
            <h3 className="text-base font-semibold mb-2 -tracking-tight">Agent fixes</h3>
            <p className="text-muted text-sm leading-relaxed">Review findings are sent back to the coding agent as structured instructions. The agent fixes issues and re-submits. Loop until clean.</p>
          </div>
        </div>
      </section>

      <hr className="border-none border-t border-edge-subtle max-w-[1200px] mx-auto" />

      {/* PRIVACY / LOCAL-FIRST */}
      <section className="max-w-[1200px] mx-auto py-16 md:py-24 px-5 md:px-8">
        <div className="grid grid-cols-1 md:grid-cols-2 gap-10 md:gap-16 items-center">
          <div>
            <span className="inline-block font-mono text-xs font-semibold tracking-widest uppercase text-amber mb-3">[ privacy-first ]</span>
            <h2 className="text-[clamp(1.75rem,4vw,2.25rem)] font-bold -tracking-wide leading-tight mb-4">Your code never leaves your machine</h2>
            <p className="text-muted text-base leading-relaxed mb-8">
              CodeVetter is a desktop app, not a SaaS. No accounts, no telemetry, no data collection.
              The only network call is to the AI provider you choose — and you control that API key.
            </p>
            <div className="flex flex-col gap-3.5">
              <div className="flex items-center gap-3 text-sm text-content">
                <CheckIcon />
                <span>Runs 100% offline (except AI API calls)</span>
              </div>
              <div className="flex items-center gap-3 text-sm text-content">
                <CheckIcon />
                <span>No CodeVetter servers — zero data collection</span>
              </div>
              <div className="flex items-center gap-3 text-sm text-content">
                <CheckIcon />
                <span>Open source — audit every line yourself</span>
              </div>
              <div className="flex items-center gap-3 text-sm text-content">
                <CheckIcon />
                <span>Use your own API key — switch providers anytime</span>
              </div>
            </div>
          </div>
          <div className="flex flex-col items-center gap-8">
            <div className="flex flex-col sm:flex-row items-center gap-6 p-8 md:p-10 bg-card border border-edge rounded-2xl w-full justify-center">
              <div className="flex flex-col items-center gap-2 p-5 rounded-xl border-[1.5px] border-dashed border-amber-border text-amber bg-amber-dim min-w-[100px]">
                <svg width="24" height="24" viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="1.5" strokeLinecap="round" strokeLinejoin="round"><rect x="2" y="3" width="20" height="14" rx="2"/><line x1="8" y1="21" x2="16" y2="21"/><line x1="12" y1="17" x2="12" y2="21"/></svg>
                <span className="font-mono text-xs font-semibold tracking-wide uppercase">Your Mac</span>
              </div>
              <div className="flex flex-col items-center gap-1">
                <svg className="sm:block hidden" width="40" height="16" viewBox="0 0 40 16"><line x1="0" y1="8" x2="34" y2="8" stroke="#2a2b35" strokeWidth="1.5" strokeDasharray="4 3"/><polygon points="34,3 40,8 34,13" fill="#5c5e6a"/></svg>
                <svg className="sm:hidden block rotate-90" width="40" height="16" viewBox="0 0 40 16"><line x1="0" y1="8" x2="34" y2="8" stroke="#2a2b35" strokeWidth="1.5" strokeDasharray="4 3"/><polygon points="34,3 40,8 34,13" fill="#5c5e6a"/></svg>
                <span className="font-mono text-[0.65rem] text-faint uppercase tracking-wider">API key only</span>
              </div>
              <div className="flex flex-col items-center gap-2 p-5 rounded-xl border-[1.5px] border-dashed border-edge text-muted bg-elevated min-w-[100px]">
                <svg width="24" height="24" viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="1.5" strokeLinecap="round" strokeLinejoin="round"><path d="M12 2a7 7 0 017 7c0 2.38-1.19 4.47-3 5.74V17a1 1 0 01-1 1H9a1 1 0 01-1-1v-2.26C6.19 13.47 5 11.38 5 9a7 7 0 017-7z"/><path d="M9 21h6"/></svg>
                <span className="font-mono text-xs font-semibold tracking-wide uppercase">AI Provider</span>
              </div>
            </div>
            <div className="flex items-center gap-2.5 font-mono text-xs text-faint tracking-wide">
              <svg width="20" height="20" viewBox="0 0 24 24" fill="none" stroke="#ef4444" strokeWidth="1.5" strokeLinecap="round" strokeLinejoin="round"><path d="M18 10h-1.26A8 8 0 105 13.4"/><line x1="1" y1="1" x2="23" y2="23"/></svg>
              <span>No cloud. No SaaS. No middleman.</span>
            </div>
          </div>
        </div>
      </section>

      <hr className="border-none border-t border-edge-subtle max-w-[1200px] mx-auto" />

      {/* FAQ */}
      <section className="max-w-[1200px] mx-auto py-16 md:py-24 px-5 md:px-8">
        <div className="grid grid-cols-1 lg:grid-cols-[1fr_2fr] gap-8 lg:gap-16 items-start">
          <div>
            <span className="inline-block font-mono text-xs font-semibold tracking-widest uppercase text-amber mb-3">[ faq ]</span>
            <h2 className="text-[clamp(1.5rem,3vw,2rem)] font-bold -tracking-wide leading-tight mb-3">Frequently Asked Questions</h2>
            <p className="text-muted text-sm mb-6">Something else on your mind?</p>
            <a
              href={`${GITHUB_URL}/discussions`}
              className="inline-flex items-center px-5 py-2.5 rounded-lg text-sm font-medium border border-edge text-content hover:bg-card hover:border-muted transition-all"
              target="_blank"
              rel="noopener noreferrer"
            >
              Ask on GitHub
            </a>
          </div>
          <div className="border-t border-edge">
            {FAQ_ITEMS.map((item, index) => (
              <AccordionItem
                key={index}
                question={item.question}
                answer={item.answer}
                isOpen={openFaq === index}
                onToggle={() => setOpenFaq(openFaq === index ? null : index)}
                isLast={index === FAQ_ITEMS.length - 1}
              />
            ))}
          </div>
        </div>
      </section>

      <hr className="border-none border-t border-edge-subtle max-w-[1200px] mx-auto" />

      {/* CTA */}
      <section className="max-w-[1200px] mx-auto py-16 md:py-24 px-5 md:px-8 text-center">
        <div className="cta-gradient relative bg-card border border-edge rounded-2xl p-12 md:p-16 overflow-hidden">
          <h2 className="text-[clamp(1.75rem,4vw,2.25rem)] font-bold -tracking-wide mb-4">Ship better code with AI agents</h2>
          <p className="text-muted text-base mb-8 leading-relaxed">Free, open source, runs offline. Requires macOS 12+ and an AI provider API key.</p>
          <div className="flex gap-3 justify-center flex-wrap">
            <a href={DOWNLOAD_URL} className="inline-flex items-center gap-2 px-7 py-3.5 rounded-xl text-base font-semibold bg-amber text-page hover:bg-amber-light hover:shadow-[0_0_20px_rgba(245,158,11,0.25)] transition-all">
              Download for macOS
            </a>
          </div>
        </div>
      </section>

      {/* FOOTER */}
      <footer className="border-t border-edge-subtle pt-12 pb-8 px-5 md:px-8">
        <div className="max-w-[1200px] mx-auto">
          <div className="flex flex-col md:flex-row justify-between gap-8 mb-12">
            <div className="flex items-center gap-2">
              <div className="w-[22px] h-[22px] bg-amber rounded-md grid place-items-center text-[0.55rem] text-page font-black -tracking-wider">CV</div>
              <span className="text-sm font-semibold">CodeVetter</span>
            </div>
            <div className="flex gap-10 md:gap-16">
              <div className="flex flex-col gap-2.5">
                <h4 className="text-xs font-semibold uppercase tracking-wider text-content mb-1">Product</h4>
                <a href={DOWNLOAD_URL} className="text-muted text-sm hover:text-content transition-colors">Download</a>
                <a href={GITHUB_URL} className="text-muted text-sm hover:text-content transition-colors" target="_blank" rel="noopener noreferrer">Source Code</a>
                <a href={`${GITHUB_URL}/releases`} className="text-muted text-sm hover:text-content transition-colors" target="_blank" rel="noopener noreferrer">Releases</a>
              </div>
              <div className="flex flex-col gap-2.5">
                <h4 className="text-xs font-semibold uppercase tracking-wider text-content mb-1">Community</h4>
                <a href={`${GITHUB_URL}/issues`} className="text-muted text-sm hover:text-content transition-colors" target="_blank" rel="noopener noreferrer">Report Bugs</a>
                <a href={`${GITHUB_URL}/discussions`} className="text-muted text-sm hover:text-content transition-colors" target="_blank" rel="noopener noreferrer">Discussions</a>
                <a href={GITHUB_URL} className="text-muted text-sm hover:text-content transition-colors" target="_blank" rel="noopener noreferrer">GitHub</a>
              </div>
            </div>
          </div>
          <div className="border-t border-edge-subtle pt-6">
            <span className="text-xs text-faint">Built by Sarthak Agrawal</span>
          </div>
        </div>
      </footer>
    </>
  );
}
