export type AgentDetectionResult = {
  isAgentAuthored: boolean;
  agentName?: string;
};

const BOT_ACCOUNT_PATTERNS = [
  /\[bot\]$/,
  /^dependabot$/i,
  /^renovate$/i,
  /^devin-ai-integration$/i,
  /^github-actions$/i,
];

const BODY_MARKERS: Array<{ pattern: RegExp; name: string }> = [
  { pattern: /Generated with \[Claude Code\]/i, name: 'claude-code' },
  { pattern: /<!-- agent:([a-z0-9_-]+) -->/i, name: '' }, // name extracted from capture group
  { pattern: /Co-Authored-By:.*claude/i, name: 'claude-code' },
  { pattern: /Generated by Devin/i, name: 'devin' },
  { pattern: /Created by Cursor/i, name: 'cursor' },
  { pattern: /\[Copilot\]/i, name: 'github-copilot' },
];

const BRANCH_PREFIXES: Array<{ prefix: string; name: string }> = [
  { prefix: 'claude/', name: 'claude-code' },
  { prefix: 'devin/', name: 'devin' },
  { prefix: 'cursor/', name: 'cursor' },
  { prefix: 'copilot-ws/', name: 'github-copilot' },
];

const COMMIT_CO_AUTHOR_PATTERNS: Array<{ pattern: RegExp; name: string }> = [
  { pattern: /Co-Authored-By:.*Claude/i, name: 'claude-code' },
  { pattern: /Co-Authored-By:.*Devin/i, name: 'devin' },
  { pattern: /Co-Authored-By:.*Copilot/i, name: 'github-copilot' },
];

export function detectAgent(opts: {
  authorLogin?: string;
  prBody?: string;
  headRef?: string;
  commitMessages?: string[];
}): AgentDetectionResult {
  const { authorLogin, prBody, headRef, commitMessages } = opts;

  // 1. Check bot accounts
  if (authorLogin) {
    for (const pattern of BOT_ACCOUNT_PATTERNS) {
      if (pattern.test(authorLogin)) {
        return { isAgentAuthored: true, agentName: authorLogin.replace(/\[bot\]$/, '').toLowerCase() };
      }
    }
  }

  // 2. Check PR body markers
  if (prBody) {
    for (const marker of BODY_MARKERS) {
      const match = prBody.match(marker.pattern);
      if (match) {
        const name = marker.name || (match[1] ? match[1].toLowerCase() : undefined);
        return { isAgentAuthored: true, agentName: name };
      }
    }
  }

  // 3. Check branch prefixes
  if (headRef) {
    for (const bp of BRANCH_PREFIXES) {
      if (headRef.startsWith(bp.prefix)) {
        return { isAgentAuthored: true, agentName: bp.name };
      }
    }
  }

  // 4. Check commit co-author patterns
  if (commitMessages && commitMessages.length > 0) {
    for (const msg of commitMessages) {
      for (const cap of COMMIT_CO_AUTHOR_PATTERNS) {
        if (cap.pattern.test(msg)) {
          return { isAgentAuthored: true, agentName: cap.name };
        }
      }
    }
  }

  return { isAgentAuthored: false };
}
